package scaffold

import (
	"bytes"
	"strings"
	"testing"

	"github.com/example/spin/internal/version"
)

// TestAGENTSmd_MarkerOnLine1 asserts the file begins with the version
// marker on the very first line, with no blank line above. The marker
// is the "owned-by-spin" signal that lets a future `spin update`
// identify and refresh spin-generated files.
func TestAGENTSmd_MarkerOnLine1(t *testing.T) {
	p := &Project{
		Name:    "myapp",
		Module:  "github.com/foo/myapp",
		Type:    "tui",
		Libs:    []string{"bubbletea", "lipgloss"},
		Year:    2026,
		SpinVer: "1.2.3",
		AI:      true,
	}

	files, err := p.renderToMap()
	if err != nil {
		t.Fatalf("renderToMap: %v", err)
	}
	agents, ok := files["AGENTS.md"]
	if !ok {
		t.Fatalf("AGENTS.md missing from render output; got keys: %v", keysOf(files))
	}

	firstLine, _, _ := strings.Cut(string(agents), "\n")
	want := "<!-- AUTOGENERATED by spin 1.2.3 -->"
	if firstLine != want {
		t.Errorf("AGENTS.md line 1 = %q, want %q", firstLine, want)
	}
}

// TestAGENTSmd_SortedLibs asserts that even when p.Libs is unsorted
// and bools are set in arbitrary order, the rendered output lists
// libraries alphabetically. This is the determinism contract: libraries
// always in the same order, regardless of flag order.
func TestAGENTSmd_SortedLibs(t *testing.T) {
	p := &Project{
		Name:    "myapp",
		Module:  "github.com/foo/myapp",
		Type:    "tui",
		Libs:    []string{"lipgloss", "bubbletea"}, // intentionally unsorted
		Cobra:   true,
		Year:    2026,
		SpinVer: "0.1.0",
		AI:      true,
	}

	files, err := p.renderToMap()
	if err != nil {
		t.Fatalf("renderToMap: %v", err)
	}
	agents := string(files["AGENTS.md"])

	// Find the byte offset of each library's H3 heading. Alphabetical
	// order is: Bubble Tea < Cobra < Lip Gloss (case-insensitive ASCII
	// sort: 'B' < 'C' < 'L').
	idxBT := strings.Index(agents, "### Bubble Tea")
	idxCB := strings.Index(agents, "### Cobra")
	idxLG := strings.Index(agents, "### Lip Gloss")

	if idxBT < 0 {
		t.Fatal("AGENTS.md missing '### Bubble Tea' heading")
	}
	if idxLG < 0 {
		t.Fatal("AGENTS.md missing '### Lip Gloss' heading")
	}
	if idxCB < 0 {
		t.Fatal("AGENTS.md missing '### Cobra' heading")
	}
	if !(idxBT < idxCB && idxCB < idxLG) {
		t.Errorf("library sections not in alphabetical order: Bubble Tea at %d, Cobra at %d, Lip Gloss at %d",
			idxBT, idxCB, idxLG)
	}
}

// TestAGENTSmd_Determinism renders the same project twice and asserts
// the bytes are identical: two scaffolds with the same flags must
// produce byte-identical output.
func TestAGENTSmd_Determinism(t *testing.T) {
	p := &Project{
		Name:    "myapp",
		Module:  "github.com/foo/myapp",
		Type:    "tui",
		Libs:    []string{"bubbletea", "bubbles", "lipgloss"},
		Cobra:   true,
		Year:    2026,
		SpinVer: version.Version,
		AI:      true,
	}

	first, err := p.renderToMap()
	if err != nil {
		t.Fatalf("first render: %v", err)
	}
	second, err := p.renderToMap()
	if err != nil {
		t.Fatalf("second render: %v", err)
	}

	firstAgents := first["AGENTS.md"]
	secondAgents := second["AGENTS.md"]
	if !bytes.Equal(firstAgents, secondAgents) {
		t.Errorf("AGENTS.md not byte-identical across renders:\n--- first ---\n%s\n--- second ---\n%s",
			firstAgents, secondAgents)
	}
}

// TestAGENTSmd_NotEmittedWithoutAI asserts the overlay walker skips
// lib/ai/ when p.AI is false, so no AGENTS.md appears in the rendered
// file map.
func TestAGENTSmd_NotEmittedWithoutAI(t *testing.T) {
	p := &Project{
		Name:    "myapp",
		Module:  "github.com/foo/myapp",
		Type:    "tui",
		Libs:    []string{"bubbletea"},
		Year:    2026,
		SpinVer: "0.1.0",
		AI:      false, // critical: opt-out
	}

	files, err := p.renderToMap()
	if err != nil {
		t.Fatalf("renderToMap: %v", err)
	}
	if _, ok := files["AGENTS.md"]; ok {
		t.Errorf("AGENTS.md emitted despite p.AI=false; file should only render when --ai is set")
	}
}

// TestAGENTSmd_NoANSI asserts the rendered AGENTS.md contains no ANSI
// escape codes, no lipgloss styles, no hex colors. Plain
// GitHub-flavored Markdown only.
func TestAGENTSmd_NoANSI(t *testing.T) {
	p := &Project{
		Name:    "myapp",
		Module:  "github.com/foo/myapp",
		Type:    "all",
		Libs:    []string{"bubbletea", "bubbles", "lipgloss"},
		Cobra:   true,
		Fang:    true,
		Viper:   true,
		Huh:     true,
		Glamour: true,
		Wish:    true,
		Log:     true,
		Year:    2026,
		SpinVer: "0.1.0",
		AI:      true,
	}

	files, err := p.renderToMap()
	if err != nil {
		t.Fatalf("renderToMap: %v", err)
	}
	agents := files["AGENTS.md"]
	for _, banned := range []string{"\033", "\x1b", "\x1B"} {
		if bytes.Contains(agents, []byte(banned)) {
			t.Errorf("AGENTS.md contains forbidden ANSI byte %q; should be plain GFM", banned)
		}
	}
	// Hex color codes (e.g. #ff00aa) shouldn't appear either. Cheap
	// check: any '#' followed by 3 or 6 hex digits is a hex color.
	for _, frag := range []string{"#FFF", "#fff", "#FF00AA", "#ff00aa", "#abcdef"} {
		if bytes.Contains(agents, []byte(frag)) {
			t.Errorf("AGENTS.md contains forbidden hex color %q; should be plain GFM", frag)
		}
	}
}

// TestCharmLibInfo_AllThirteen asserts charmLibInfo returns a non-empty
// module string for every key in the library lookup table. A missing
// entry would mean a regression in the lookup table (e.g. a typo
// in the switch case).
func TestCharmLibInfo_AllThirteen(t *testing.T) {
	fm := funcMap(&Project{AI: true})
	fn, ok := fm["charmLibInfo"].(func(string, string) string)
	if !ok {
		t.Fatal("funcMap missing charmLibInfo helper")
	}

	wantKeys := []string{
		"bubbletea", "bubbles", "lipgloss", "huh", "glamour",
		"wish", "log", "harmonica", "cobra", "fang", "viper",
		"ansi", "runewidth",
	}
	for _, key := range wantKeys {
		if mod := fn(key, "module"); mod == "" {
			t.Errorf("charmLibInfo(%q, \"module\") = \"\"; module path missing for key %q", key, key)
		}
		if display := fn(key, "display"); display == "" {
			t.Errorf("charmLibInfo(%q, \"display\") = \"\"; display name missing for key %q", key, key)
		}
		if purpose := fn(key, "purpose"); purpose == "" {
			t.Errorf("charmLibInfo(%q, \"purpose\") = \"\"; purpose missing for key %q", key, key)
		}
		if extending := fn(key, "extending"); extending == "" {
			t.Errorf("charmLibInfo(%q, \"extending\") = \"\"; extending guidance missing for key %q", key, key)
		}
		if example := fn(key, "example"); example == "" {
			t.Errorf("charmLibInfo(%q, \"example\") = \"\"; example code missing for key %q", key, key)
		}
	}
}

// TestCharmLibInfo_UnknownReturnsEmpty asserts unknown library names
// and unknown field selectors return "". Same contract as charmPin.
func TestCharmLibInfo_UnknownReturnsEmpty(t *testing.T) {
	fm := funcMap(&Project{AI: true})
	fn := fm["charmLibInfo"].(func(string, string) string)

	if got := fn("nonexistent", "display"); got != "" {
		t.Errorf("charmLibInfo(\"nonexistent\", \"display\") = %q, want \"\"", got)
	}
	if got := fn("bubbletea", "nonexistent_field"); got != "" {
		t.Errorf("charmLibInfo(\"bubbletea\", \"nonexistent_field\") = %q, want \"\"", got)
	}
}

// TestAllLibsFuncMap asserts the allLibs FuncMap helper delegates to
// p.AllLibs() correctly. AGENTS.md iterates this for library sections.
func TestAllLibsFuncMap(t *testing.T) {
	p := &Project{
		Libs:  []string{"bubbletea", "lipgloss"},
		Cobra: true,
		Huh:   true,
	}
	fm := funcMap(p)
	fn, ok := fm["allLibs"].(func(*Project) []string)
	if !ok {
		t.Fatal("funcMap missing allLibs helper")
	}
	got := fn(p)
	want := []string{"bubbletea", "cobra", "huh", "lipgloss"}
	if !equalStringSlice(got, want) {
		t.Errorf("allLibs(p) = %v, want %v", got, want)
	}
}

// equalStringSlice reports whether two []string are equal (same length
// and same elements in the same order). Avoids pulling in
// reflect.DeepEqual which would also accept nil and empty as equal.
func equalStringSlice(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
