// Package scaffold implements the spin scaffolder.
//
// Project is the single source of truth for scaffold inputs: it captures
// the name/module/type/libs/license/force/etc. that cmd/new.go extracts
// from CLI flags and that internal/scaffold/* consumes during template
// rendering.
package scaffold

import "sort"

// Project is the single source of truth for scaffold inputs.
type Project struct {
	Name string
	Module string
	// Type is the project variant: "tui" | "cli" | "all".
	Type string
	// Libs is the ordered list of charm v2 libraries. Sorted and
	// deduped by ResolveFlags.
	Libs []string
	// License is the LICENSE file to emit: "mit" | "apache-2.0" | "none".
	// "none" suppresses LICENSE emission. Default is "mit".
	License string
	// Template is the template name (e.g. "tui-bubbletea"). Default
	// is "tui-bubbletea".
	Template string
	// ExternalDir is the on-disk path of a cloned template repo
	// (--template-repo). Empty by default; the walker reads from the
	// package embed when empty. Pipeline-internal — set by runNew
	// after CloneTemplateRepo succeeds; the currentFS helper reads it.
	ExternalDir string
	// KeepTemplateCache, when true, retains the cloned template repo
	// on disk after scaffolding completes (debug aid).
	KeepTemplateCache bool
	// TemplateRepo is the user-supplied git URL from --template-repo.
	// Format validated by IsValidTemplateRepo before any clone.
	TemplateRepo string
	// Force overwrites an existing ./<name>/ directory (SCAF-08).
	Force bool
	// NoGit skips the post-scaffold `git init` + initial commit.
	NoGit bool
	// NoVerify skips the post-scaffold `go build ./...` smoke test.
	NoVerify bool
	// Quiet reduces scaffolder output (charm/log v2 levels).
	Quiet bool
	// NoInteractive disables interactive prompts (--no-interactive /
	// --yes / --batch). Read in cmd/new.go's runNew before calling
	// prompt.Fill — Fill itself does NOT consult this field; the
	// split keeps the three-layer guard (env/TTY/CI) independent of
	// flag plumbing.
	NoInteractive bool
	// Year is the current year (used in generated LICENSE / README footers).
	Year int
	// SpinVer is the spin version emitted in `// generated by spin X.Y.Z`
	// markers and the generated README footer.
	SpinVer string

	// Forward-compat booleans (Phase 2/3/4). All default to false. Flag
	// binding exists today; template content is added in the corresponding
	// phase.

	Cobra bool
	Fang  bool
	Viper bool

	// Huh / Glamour / Wish / Log / Harmonica are charm library flags.
	Huh       bool
	Glamour   bool
	Wish      bool
	Log       bool
	Harmonica bool

	// Ansi / Runewidth are charmbracelet/x subpackage flags.
	Ansi      bool
	Runewidth bool

	// AI is the AGENTS.md / AI assistant opt-in (Phase 3).
	AI bool
}

// AllLibs returns the unified library set: p.Libs union the 8 bool-flag
// libs (Cobra, Fang, Viper, Huh, Glamour, Wish, Log, Harmonica),
// deduped and sorted. Single source of truth for "what libs does this
// project include?" — fixes the two-parallel-sources bug from
// 03-RESEARCH.md Pitfall 4.
//
// overlayOrder in template.go is intentionally kept on its own
// implementation (refactoring it to use AllLibs is a low-risk change
// but was deferred to avoid coupling this plan to TOOL-05 invariants).
//
// Returns a fresh slice; empty (not nil) for a zero *Project so callers
// can range without nil-checking.
func (p *Project) AllLibs() []string {
	seen := map[string]bool{}
	out := []string{}
	for _, lib := range p.Libs {
		if !seen[lib] {
			seen[lib] = true
			out = append(out, lib)
		}
	}
	for lib, active := range p.libBoolMap() {
		if active && !seen[lib] {
			seen[lib] = true
			out = append(out, lib)
		}
	}
	sort.Strings(out)
	return out
}

// libBoolMap returns the FULL mapping of per-lib bool fields to library
// names — including the libs that no longer have lib/<name>/ overlay
// directories (cobra, fang, viper, huh, glamour, wish, log, harmonica).
// This is the parallel source of truth for "is this lib selected?"
// queries the overlay walker does not cover.
//
// Plan 02-05 split this from boolFlagOverlayMap (template.go): the
// overlay map returns only bools that still have a lib/<name>/ overlay
// (just "ai" now); this one returns the full 8-entry set used by AllLibs.
func (p *Project) libBoolMap() map[string]bool {
	return map[string]bool{
		"cobra":     p.Cobra,
		"fang":      p.Fang,
		"viper":     p.Viper,
		"huh":       p.Huh,
		"glamour":   p.Glamour,
		"wish":      p.Wish,
		"log":       p.Log,
		"harmonica": p.Harmonica,
	}
}
