// Package scaffold implements the spin scaffolder.
//
// Project is the single source of truth for scaffold inputs: it captures the
// name/module/type/libs/license/force/etc. that cmd/new.go extracts from CLI
// flags and the fields that internal/scaffold/* consumes during template
// rendering.
//
// Walking Skeleton fields: Name, Module, Type, Libs, Year, SpinVer.
// Plan 02 expands with License, Template, Force, NoGit, NoVerify, Quiet, and
// the forward-compatibility booleans (Cobra, Fang, Viper, Huh, Glamour, Glow,
// Wish, Log, Harmonica, Modifiers, Ansi, Runewidth, AI) so the template
// engine and flag binding don't churn when later phases add content.
package scaffold

// Project is the single source of truth for scaffold inputs.
//
// TMPL-07 fields (per PROJECT.md / RESEARCH §4.4): Name, Module, Type, Libs,
// License, Template. Walking Skeleton fields: Year, SpinVer. Plan 02 adds
// Force, NoGit, NoVerify, Quiet, and the 13 forward-compat booleans.
type Project struct {
	// Name is the directory name (e.g. "myapp") and the default module
	// segment when Module is empty.
	Name string

	// Module is the go.mod module path. Defaults to Name when empty.
	Module string

	// Type is the project variant: "tui" | "cli" | "all".
	// Walking Skeleton supports only "tui"; Plan 02 adds "cli" and "all".
	Type string

	// Libs is the ordered list of charm v2 libraries to include.
	// Sorted and deduped by ResolveFlags. Walking Skeleton supports only
	// "bubbletea"; Plan 02 expands to bubbles, lipgloss, etc.
	Libs []string

	// License is the LICENSE file to emit: "mit" | "apache-2.0" | "none".
	// "none" suppresses LICENSE emission. Default is "mit".
	License string

	// Template is the template name (e.g. "tui-bubbletea"). Default is
	// "tui-bubbletea". Plan 02 only ships one; Phase 2 adds more.
	Template string

	// ExternalDir is the on-disk path of a cloned template repo
	// (--template-repo). Empty by default; the template walker reads
	// from the package embed (FS in scaffold.go) when ExternalDir is
	// empty. Populated by runNew after CloneTemplateRepo succeeds.
	//
	// This is a pipeline-internal field: callers do not set it
	// directly. It is set by the --template-repo flag handler in
	// runNew (cmd/new.go) once the git clone + _base/ validation
	// passes. The currentFS helper (fs.go) reads this field.
	ExternalDir string

	// KeepTemplateCache, when true, retains the cloned template repo
	// on disk after scaffolding completes. Useful for debugging a
	// broken template repo. When false (the default), runNew
	// schedules os.RemoveAll(ExternalDir) on completion.
	//
	// This is a pipeline-internal field: callers do not set it
	// directly. It is set by the --keep-template-cache flag handler
	// in ResolveFlags.
	KeepTemplateCache bool

	// Force overwrites an existing ./<name>/ directory (SCAF-08). When
	// false, Project.Validate returns an error if the dir exists.
	Force bool

	// NoGit skips the post-scaffold `git init` + initial commit.
	// Useful for tests and for users who prefer to init their own repo.
	NoGit bool

	// NoVerify skips the post-scaffold `go build ./...` smoke test.
	// Power-user escape hatch; default keeps the "perfect first run"
	// promise intact.
	NoVerify bool

	// Quiet reduces scaffolder output (charm/log v2 levels).
	Quiet bool

	// Year is the current year (used in generated LICENSE / README footers).
	Year int

	// SpinVer is the spin version emitted in `// generated by spin X.Y.Z`
	// markers and the generated README footer.
	SpinVer string

	// Forward-compat booleans (Phase 2/3/4). All default to false. Flag
	// binding exists today; template content is added in the corresponding
	// phase. Kept on the struct so the scaffolder doesn't churn when later
	// phases wire their content.

	// Cobra / Fang / Viper are CLI framework flags (Phase 2).
	Cobra bool
	Fang  bool
	Viper bool

	// Huh / Glamour / Glow / Wish / Log / Harmonica are charm library flags (Phase 2).
	// Huh is interactive forms; Glamour is markdown rendering; Glow is the
	// markdown reader binary; Wish is SSH server; Log is structured logger;
	// Harmonica is spring animations.
	Huh       bool
	Glamour   bool
	Glow      bool
	Wish      bool
	Log       bool
	Harmonica bool

	// Modifiers / Ansi / Runewidth are charmbracelet/x subpackage flags (Phase 2).
	Modifiers bool
	Ansi      bool
	Runewidth bool

	// AI is the AGENTS.md / AI assistant opt-in (Phase 3).
	AI bool
}
