// Package scaffold implements the spin scaffolder.
//
// Project is the single source of truth for scaffold inputs: it captures the
// name/module/type/libs that cmd/new.go extracts from CLI flags and the fields
// that internal/scaffold/* consumes during template rendering.
//
// Walking Skeleton fields (this file): Name, Module, Type, Libs, Year, SpinVer.
// Plan 02 expands with License, Template, Force, NoGit, Quiet, and the
// forward-compatibility booleans (Cobra, Fang, Viper, Huh, Glamour, Glow,
// Wish, Log, Harmonica, Modifiers, Ansi, Runewidth, AI) so the template
// engine and flag binding don't churn when later phases add content.
package scaffold

// Project is the single source of truth for scaffold inputs.
//
// TMPL-07 fields (per PROJECT.md / RESEARCH §4.4): Name, Module, Type, Libs.
// Walking Skeleton fields: Year, SpinVer.
type Project struct {
	// Name is the directory name (e.g. "myapp") and the default module
	// segment when Module is empty.
	Name string

	// Module is the go.mod module path. Defaults to Name when empty.
	Module string

	// Type is the project variant: "tui" | "cli" | "all".
	// Walking Skeleton supports only "tui"; Plan 02 adds "cli" and "all".
	Type string

	// Libs is the ordered list of charm v2 libraries to include.
	// Walking Skeleton supports only "bubbletea"; Plan 02 expands.
	Libs []string

	// Year is the current year (used in generated LICENSE / README footers).
	Year int

	// SpinVer is the spin version emitted in `// generated by spin X.Y.Z`
	// markers and the generated README footer.
	SpinVer string
}
